--2018-09-04 JOSÉ ALFONSO MOSCO HERRERA--
-- VERSIÓN DE LAS BUENAS PRÁCTICAS--
CREATE DATABASE ExamenUPIICSA
USE ExamenUPIICSA
-- TABLA DE USUARIOS  
CREATE TABLE TBL001_USUARIOS
(
	ID_USUARIO INT IDENTITY NOT NULL PRIMARY KEY, -- ID DEL USUARIO UNICO 
	USUARIO VARCHAR(30) NOT NULL,
	CONTRASENA VARCHAR(30) NOT NULL
	EMAIL VARCHAR(100) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO1 VARCHAR(50) NOT NULL,
	APELLIDO2 VARCHAR(50) NULL,
	SEXO VARCHAR(10) NOT NULL,
	EDAD INT NOT NULL,
	STATUS BIT NOT NULL,
);

-- TABLA DE TIPOS (JERARQUIAS)
CREATE TABLE TBL002_TIPOS
(
	ID_TIPO INT IDENTITY NOT NULL PRIMARY KEY, --1,2,3
	NOM_TIPO VARCHAR NOT NULL -- ALUMNO, PROFESOR, ADMIN
);

INSET INTO TBL002_TIPOS VALUES(1,'ADMIN'),(2,'PROFESOR'),(3,'ALUMNO');

-- TENDRÁ QUE EXISTIR UN SP QUE VALIDE SELECTCOUNT(*) AQUI PARA VER QUE TIPO DE USUARIO ESTAMOS HABLANDO
CREATE TABLE TBL003_TIPOS_USUARIOS
(
	ID_USUARIO INT,
	ID_TIPO INT,
	FOREIGN KEY(ID_USUARIO) REFERENCES TBL001_USUARIOS(ID_USUARIO);
	FOREIGN KEY(ID_TIPO) REFERENCES TBL002_TIPOS(ID_TIPO);
)

--QUERY CONSULTA
SELECT u.USUARIO, t.NOM_TIPO
  FROM TBL001_USUARIOS u
  LEFT JOIN TBL003_TIPOS_USUARIOS ut 
      ON u.ID_USUARIO = ut.ID_USUARIO
  LEFT JOIN tipo t 
      ON t.TBL002_TIPOS= ut.ID_TIPO   




----SIMPLIFICADO (VERSIÓN YOLO)---
CREATE DATABASE PerfilMetaCognitivoUPIICSA

USE PerfilMetaCognitivoUPIICSA

CREATE TABLE USUARIOS
(	
	USUARIO VARCHAR(30) NOT NULL PRIMARY KEY,
	TIPO_USUARIO VARCHAR(15)
					CHECK(TIPO_USUARIO IN ('ADMIN','PROFESOR','ALUMNO') NOT NULL, -- EL ENUM DE SQL SERVER :V 
	CONTRASENA VARCHAR(30) NOT NULL,
	GRUPO VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO1 VARCHAR(50) NOT NULL,
	APELLIDO2 VARCHAR(50) NULL,
	SEXO VARCHAR(10) NOT NULL, -- ES POSIBLE QUE NO SE NECESITE
	EDAD INT NOT NULL, -- IGUAL Y TAMPOCO SE NECESITA
);

--GRUPOS
-- ESTA TABLA NECESITA SER REVISADA
CREATE TABLE GRUPO
(
	ID_GRUPO VARCHAR(30) NOT NULL,
	SECUENCIA VARCHAR(30) NOT NULL,
	USUARIO VARCHAR(30) NOT NULL,
);

CREATE TABLE INTELIGENCIAS_MULTIPLES
(
	CLAVE VARCHAR(10) NOT NULL PRIMARY KEY,
	CONCEPTO VARCHAR(50) NOT NULL ,
	DEFINICION VARCHAR(1000) NOT NULL,
	REFERENCIA INT NOT NULL,
	RESULTADO INT NOT NULL
);

CREATE TABLE INTELIGENCIA_EMOCIONAL
(
	CLAVE VARCHAR(10) NOT NULL PRIMARY KEY,
	CONCEPTO VARCHAR(50) NOT NULL,
	DEFINICION VARCHAR(1000) NOT NULL,
	REFERENCIA INT NOT NULL, -- LOS RESULTADOS SE PROMEDIAN Y SE VAN A COMPARAR RESULTADO >= QUE REFERNCIA, SACAR RANGOS
	RESULTADO INT NOT NULL
);
-----
CREATE TABLE PREGUNTAS
